#include "wled.h"

/*
 * PresenceSwitch usermod
 *
 * Periodically pings a user-selected list of devices on the local network (identified by IPv4
 * address). If none of the watched devices have answered for a configurable amount of time, WLED
 * is switched off. As soon as any watched device answers again, WLED is switched back on.
 *
 * The usermod can also perform a one-off scan of the local /24 subnet (triggered automatically
 * shortly after Wi-Fi connects, or on demand via {"PresenceSwitch":{"scan":true}} sent to
 * /json/state). Devices that answer the scan are offered as checkboxes on the Usermod Settings
 * page so the user can pick which ones to watch.
 *
 * Network scanning/pinging uses the ESP-IDF "ping_sock" API and is therefore ESP32-only; on
 * ESP8266 the usermod compiles but presence detection is always reported as "absent".
 *
 * Devices are identified purely by IPv4 address (not MAC), so for reliable long-term tracking
 * configure a DHCP reservation for the watched devices on your router.
 */

// AI: below section was generated by an AI

#ifdef ARDUINO_ARCH_ESP32
#include "ping/ping_sock.h"
#include "lwip/ip_addr.h"
#include "lwip/ip4_addr.h"
#endif

#include <vector>
#include <algorithm>

#ifndef PRESENCE_MAX_DEVICES
#define PRESENCE_MAX_DEVICES 16 // max number of checkboxes shown on the settings page (buffer is limited)
#endif
#define PRESENCE_PING_TIMEOUT_MS 800 // max time to wait for a single ping reply
#define PRESENCE_SCAN_HOST_MAX 254   // scan x.x.x.1 - x.x.x.254 of the local /24

class PresenceSwitchUsermod : public Usermod
{
private:
    enum class Mode : uint8_t
    {
        IDLE,
        SCAN,
        PRESENCE
    };

    // config
    bool enabled = true;
    uint16_t offDelayMin = 10;      // minutes with no watched device present before switching off (0 = never)
    uint16_t checkIntervalSec = 30; // how often watched devices are (re-)pinged

    // devices the user selected to be watched, and devices found during the last scan
    // (both are keys built by ipToKey(), RAM only for foundIPs)
    std::vector<uint32_t> watchedIPs;
    std::vector<uint32_t> foundIPs;

    // ping engine state machine (shared by scan and presence-check rounds)
    Mode mode = Mode::IDLE;
    std::vector<uint32_t> queue;
    size_t queueIndex = 0;
    bool pingBusy = false;
    volatile bool pingGotReply = false;
    unsigned long pingStarted = 0;
#ifdef ARDUINO_ARCH_ESP32
    esp_ping_handle_t pingHandle = nullptr;
#endif

    // presence result
    bool anyPresent = false;
    unsigned long lastSeenTime = 0;
    unsigned long lastFullCheck = 0;
    bool switchedOffByMod = false;
    uint8_t restoreBri = 128;

    // auto-scan shortly after (re)connecting, if nothing has been found yet
    bool wantAutoScan = false;
    unsigned long autoScanRequestedAt = 0;

    bool initDone = false;

    static const char _name[];
    static const char _enabled[];
    static const char _offDelay[];
    static const char _interval[];

    static uint32_t ipToKey(const IPAddress &ip)
    {
        return ((uint32_t)ip[0] << 24) | ((uint32_t)ip[1] << 16) | ((uint32_t)ip[2] << 8) | (uint32_t)ip[3];
    }
    static IPAddress keyToIp(uint32_t k)
    {
        return IPAddress((k >> 24) & 0xFF, (k >> 16) & 0xFF, (k >> 8) & 0xFF, k & 0xFF);
    }

    void startPing(const IPAddress &ip);
    void advanceQueue();
    void finishQueue();
    void beginScan();
    void beginPresenceRound();
    void applySwitch(bool on);

#ifdef ARDUINO_ARCH_ESP32
    static void onPingSuccessCb(esp_ping_handle_t hdl, void *args);
    static void onPingEndCb(esp_ping_handle_t hdl, void *args);
#endif

public:
    void setup() override
    {
        lastSeenTime = millis(); // start the "absent" timer from boot, not from an unset value
        initDone = true;
    }

    void connected() override
    {
        // give the network stack a moment, then scan automatically if we don't know any devices yet
        wantAutoScan = true;
        autoScanRequestedAt = millis();
    }

    void loop() override;

    void addToJsonInfo(JsonObject &root) override
    {
        JsonObject user = root["u"];
        if (user.isNull())
            user = root.createNestedObject("u");

        JsonArray state = user.createNestedArray(FPSTR(_name));
        if (!enabled)
        {
            state.add(F("disabled"));
        }
        else
        {
            state.add(anyPresent ? F("present") : F("absent"));
            if (watchedIPs.empty())
                state.add(F(" (no devices watched)"));
        }
    }

    void addToJsonState(JsonObject &root) override
    {
        if (!initDone)
            return;
        JsonObject um = root[FPSTR(_name)];
        if (um.isNull())
            um = root.createNestedObject(FPSTR(_name));
        um["present"] = anyPresent;
        um["scanning"] = (mode == Mode::SCAN);
    }

    void readFromJsonState(JsonObject &root) override
    {
        if (!initDone)
            return;
        JsonObject um = root[FPSTR(_name)];
        if (um.isNull())
            return;
        if (um["scan"] | false)
            beginScan();
    }

    void addToConfig(JsonObject &root) override
    {
        JsonObject top = root.createNestedObject(FPSTR(_name));
        top[FPSTR(_enabled)] = enabled;
        top[FPSTR(_offDelay)] = offDelayMin;
        top[FPSTR(_interval)] = checkIntervalSec;

        // union of watched + found devices so the settings page can offer a checkbox for each
        std::vector<uint32_t> shown = watchedIPs;
        for (uint32_t k : foundIPs)
        {
            if (std::find(shown.begin(), shown.end(), k) == shown.end())
                shown.push_back(k);
        }
        if (shown.size() > PRESENCE_MAX_DEVICES)
            shown.resize(PRESENCE_MAX_DEVICES);

        for (uint32_t k : shown)
        {
            IPAddress ip = keyToIp(k);
            char key[24];
            snprintf(key, sizeof(key), "ip_%u_%u_%u_%u", ip[0], ip[1], ip[2], ip[3]);
            bool watched = std::find(watchedIPs.begin(), watchedIPs.end(), k) != watchedIPs.end();
            top[key] = watched;
        }
    }

    bool readFromConfig(JsonObject &root) override
    {
        JsonObject top = root[FPSTR(_name)];
        bool configComplete = !top.isNull();

        configComplete &= getJsonValue(top[FPSTR(_enabled)], enabled, true);
        configComplete &= getJsonValue(top[FPSTR(_offDelay)], offDelayMin, 10);
        configComplete &= getJsonValue(top[FPSTR(_interval)], checkIntervalSec, 30);

        // dynamic "ip_a_b_c_d" checkbox fields are not known ahead of time, so scan for them directly
        watchedIPs.clear();
        if (!top.isNull())
        {
            for (JsonPair kv : top)
            {
                const char *key = kv.key().c_str();
                if (strncmp(key, "ip_", 3) != 0)
                    continue;
                unsigned a, b, c, d;
                if (sscanf(key + 3, "%u_%u_%u_%u", &a, &b, &c, &d) == 4 && kv.value().as<bool>())
                {
                    watchedIPs.push_back(ipToKey(IPAddress(a, b, c, d)));
                }
            }
        }
        return configComplete;
    }

    void appendConfigData() override
    {
        String nm = String(FPSTR(_name));

        oappend(F("addInfo('"));
        oappend(nm.c_str());
        oappend(F(":"));
        oappend(String(FPSTR(_offDelay)).c_str());
        oappend(F("',1,'minutes with no watched device present before switching off (0 = never)');"));

        oappend(F("addInfo('"));
        oappend(nm.c_str());
        oappend(F(":"));
        oappend(String(FPSTR(_interval)).c_str());
        oappend(F("',1,'seconds between presence checks');"));

        std::vector<uint32_t> shown = watchedIPs;
        for (uint32_t k : foundIPs)
        {
            if (std::find(shown.begin(), shown.end(), k) == shown.end())
                shown.push_back(k);
        }
        if (shown.size() > PRESENCE_MAX_DEVICES)
            shown.resize(PRESENCE_MAX_DEVICES);

        if (shown.empty())
        {
            oappend(F("addInfo('"));
            oappend(nm.c_str());
            oappend(F(":"));
            oappend(String(FPSTR(_interval)).c_str());
            oappend(F("',1,'No devices known yet - WLED scans the local network shortly after connecting to Wi-Fi. Send scan:true in the state API to rescan.');"));
        }
        else
        {
            for (uint32_t k : shown)
            {
                IPAddress ip = keyToIp(k);
                char key[24];
                snprintf(key, sizeof(key), "ip_%u_%u_%u_%u", ip[0], ip[1], ip[2], ip[3]);
                bool present = std::find(foundIPs.begin(), foundIPs.end(), k) != foundIPs.end();
                oappend(F("addInfo('"));
                oappend(nm.c_str());
                oappend(F(":"));
                oappend(key);
                oappend(F("',1,'"));
                oappend(ip.toString().c_str());
                oappend(present ? F(" - seen in last scan');") : F(" - not seen in last scan');"));
            }
        }
    }

    uint16_t getId() override { return USERMOD_ID_PRESENCE_SWITCH; }
};

const char PresenceSwitchUsermod::_name[] PROGMEM = "PresenceSwitch";
const char PresenceSwitchUsermod::_enabled[] PROGMEM = "enabled";
const char PresenceSwitchUsermod::_offDelay[] PROGMEM = "offDelayMin";
const char PresenceSwitchUsermod::_interval[] PROGMEM = "checkIntervalSec";

void PresenceSwitchUsermod::applySwitch(bool on)
{
    if (on)
    {
        if (!switchedOffByMod)
            return; // only turn back on if we were the ones who turned it off
        bri = restoreBri;
        switchedOffByMod = false;
    }
    else
    {
        if (bri == 0)
            return;
        restoreBri = bri;
        bri = 0;
        switchedOffByMod = true;
    }
    stateUpdated(CALL_MODE_BUTTON);
}

#ifdef ARDUINO_ARCH_ESP32
void PresenceSwitchUsermod::onPingSuccessCb(esp_ping_handle_t hdl, void *args)
{
    PresenceSwitchUsermod *self = (PresenceSwitchUsermod *)args;
    self->pingGotReply = true;
}

void PresenceSwitchUsermod::onPingEndCb(esp_ping_handle_t hdl, void *args)
{
    PresenceSwitchUsermod *self = (PresenceSwitchUsermod *)args;
    self->pingBusy = false;
}
#endif

void PresenceSwitchUsermod::startPing(const IPAddress &ip)
{
    pingGotReply = false;
    pingStarted = millis();
#ifdef ARDUINO_ARCH_ESP32
    if (pingHandle)
    {
        esp_ping_delete_session(pingHandle);
        pingHandle = nullptr;
    }

    ip_addr_t target;
    memset(&target, 0, sizeof(target));
    IP4_ADDR(ip_2_ip4(&target), ip[0], ip[1], ip[2], ip[3]);
    target.type = IPADDR_TYPE_V4;

    esp_ping_config_t config = ESP_PING_DEFAULT_CONFIG();
    config.target_addr = target;
    config.count = 1;
    config.timeout_ms = PRESENCE_PING_TIMEOUT_MS;
    config.interval_ms = 0;

    esp_ping_callbacks_t cbs = {};
    cbs.cb_args = this;
    cbs.on_ping_success = onPingSuccessCb;
    cbs.on_ping_timeout = nullptr;
    cbs.on_ping_end = onPingEndCb;

    pingBusy = (esp_ping_new_session(&config, &cbs, &pingHandle) == ESP_OK);
    if (pingBusy)
        esp_ping_start(pingHandle);
#else
    (void)ip;
    pingBusy = false; // ESP8266: ping engine not implemented, always reports "not found"
#endif
}

void PresenceSwitchUsermod::finishQueue()
{
    mode = Mode::IDLE;
    queue.clear();
#ifdef ARDUINO_ARCH_ESP32
    if (pingHandle)
    {
        esp_ping_delete_session(pingHandle);
        pingHandle = nullptr;
    }
#endif
}

void PresenceSwitchUsermod::advanceQueue()
{
    bool success = pingGotReply;

    if (mode == Mode::SCAN)
    {
        uint32_t k = queue[queueIndex];
        if (success && foundIPs.size() < PRESENCE_MAX_DEVICES &&
            std::find(foundIPs.begin(), foundIPs.end(), k) == foundIPs.end())
        {
            foundIPs.push_back(k);
        }
    }
    else if (mode == Mode::PRESENCE)
    {
        if (success)
        {
            anyPresent = true;
            lastSeenTime = millis();
            finishQueue(); // no need to probe the remaining watched devices this round
            return;
        }
    }

    queueIndex++;
    if (queueIndex >= queue.size())
    {
        if (mode == Mode::PRESENCE)
            anyPresent = false; // none of the watched devices answered
        finishQueue();
        return;
    }
    startPing(keyToIp(queue[queueIndex]));
}

void PresenceSwitchUsermod::beginScan()
{
    if (mode != Mode::IDLE || !WLED_CONNECTED)
        return;

    IPAddress local = Network.localIP();
    queue.clear();
    for (uint16_t h = 1; h <= PRESENCE_SCAN_HOST_MAX; h++)
    {
        if (h == local[3])
            continue; // skip our own address
        queue.push_back(ipToKey(IPAddress(local[0], local[1], local[2], (uint8_t)h)));
    }
    foundIPs.clear();
    queueIndex = 0;
    mode = Mode::SCAN;
    startPing(keyToIp(queue[0]));
}

void PresenceSwitchUsermod::beginPresenceRound()
{
    if (mode != Mode::IDLE || !WLED_CONNECTED)
        return;
    if (watchedIPs.empty())
    {
        anyPresent = false;
        return;
    }

    queue = watchedIPs;
    queueIndex = 0;
    mode = Mode::PRESENCE;
    startPing(keyToIp(queue[0]));
}

void PresenceSwitchUsermod::loop()
{
    if (!initDone || !enabled)
        return;
    unsigned long now = millis();

    if (mode != Mode::IDLE)
    {
        if (pingBusy)
        {
            // safety net in case the underlying callback never fires
            if (now - pingStarted > (unsigned long)PRESENCE_PING_TIMEOUT_MS + 500)
            {
                pingBusy = false;
                pingGotReply = false;
            }
            else
            {
                return;
            }
        }
        advanceQueue();
        return;
    }

    if (!WLED_CONNECTED)
        return;

    if (wantAutoScan && now - autoScanRequestedAt > 5000)
    {
        wantAutoScan = false;
        if (foundIPs.empty())
            beginScan();
    }

    if (now - lastFullCheck >= (unsigned long)checkIntervalSec * 1000UL)
    {
        lastFullCheck = now;
        beginPresenceRound();
    }

    if (offDelayMin > 0 && !watchedIPs.empty())
    {
        if (!anyPresent && (now - lastSeenTime > (unsigned long)offDelayMin * 60000UL))
        {
            applySwitch(false);
        }
        else if (anyPresent && switchedOffByMod)
        {
            applySwitch(true);
        }
    }
}

static PresenceSwitchUsermod presence_switch_usermod;
REGISTER_USERMOD(presence_switch_usermod);
// AI: end
